runtime: nodejs20
instance_class: F1

automatic_scaling:
  max_instances: 1
  
handlers:
  - url: /tags\.json
    static_files: tags.json
    upload: tags\.json
    
  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  - url: /(.*)
    static_files: dist/\1
    upload: dist/(.*)